title: Rain Deep Sleep
description: Calm rain ambience for sleep, focus, and relaxation.

baseurl: "/rain-deep-sleep"
url: "https://choijangwook.github.io"

permalink: /:year-:month-:day-:title/

markdown: kramdown

theme: minima

plugins:
  - jekyll-feed
